ci:
  autoupdate_commit_msg: "MAINT: autoupdate pre-commit hooks"
  autoupdate_schedule: quarterly
  skip:
    - prettier
    - taplo

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/ComPWA/policy
    rev: 0.2.0
    hooks:
      - id: check-dev-files
        args:
          - --ignore-author
          - --no-github-actions
          - --no-gitpod
          - --no-prettierrc
          - --no-python
          - --no-version-branches
          - --repo-name=mirrors-taplo

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: https://github.com/ComPWA/mirrors-taplo
    rev: v0.8.1
    hooks:
      - id: taplo

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort
        args:
          - --in-place
